# C2 — Session 25 item 2, UNIT B (`Separation5`): clause 5 of Theorem M2 — the rung (summability), 1(a) (clause 5 modulo H-R₀ = 73), 1(b) + Piece 8 (H-R₀ discharged by a 16-cell Z enclosure) — build notes (Job 1, BUILDER, Fable 5.1; Session 25, 2026-09-24, 22:09–23:10 IST)

Brief: `results/c2-m4/BRIEF-B.md`. Contract: `results/c2-m4/PRICING-RESIDUE.md` §1 Piece 1 (items 1–11), Piece 8 (n = 16), §2 row B, §3's Unit-B paragraph. Mathematics: `results/c2-m2/separation-note.md` §6 (clause 5 (a), (b), "The sums", "The relaxation …") and addendum A3 (R₀ = 73, exponent 13/8, F₁₃(50) = −0.3227, decrease from L = 6.113); `check-O.md` §7 (steps 1–10), §7.3 (i) (P is a Laurent polynomial), §12.7–§12.8; `verify/r0_73_check.py` lines 22–33 + `r0_73_check_run.log`. Pattern: Unit A (`BUILD-NOTES-A.md`, `SHARED.md`, `verify-A/`, `CHECK-O-A.md`), repeated with the suffix `-B`. Tree `~/rh-lean-work/zeta-23-lean-main` (Lean `v4.33.0-rc2`, Mathlib `51e6992e`), mirror `rh-program/lean/` (`cmp`-identical for every file below; `verify-B/untouched.log`). Not independently checked yet: Job 2 (Opus 5, clean clone; `CHECK-O-B.md`) is the next step. No commit by this job (the watchdogs commit). Stage log with machine-clock timestamps: `results/c2-m4/SHARED.md` (the Unit B blocks, stages 0–7). Nothing here is about ζ, RH or the prime side.

**Labels, verbatim and binding (PRICING-RESIDUE §2 row B):** after the rung, "clause 5's summability is Comparator-checked"; after 1(a), **"Theorem M2's clause-6 assembly is a Comparator-checked theorem over `SepConfig`, modulo the displayed H-edge, H-B‴ and H-R₀ (the one-point check F₁₃(50; 73) ≤ 0 as a displayed real inequality), on the three standard axioms, replayed by nanoda"**; after 1(b), the label this unit SHIPS: **"Theorem M2's clause-6 assembly is a Comparator-checked theorem over `SepConfig`, modulo the displayed H-edge and H-B‴, on the three standard axioms, replayed by nanoda"** — never "clause 5 is formalized", never "Theorem M2 is formalized" (clause 8's ζ instance `zeta_in_class_C1` is not stated; the fidelity rows (p)–(r) remain).

## 0. Which legs landed (brief §"Deliverables"): ALL THREE — the rung, 1(a), 1(b) + Piece 8; no stop line fired

| leg | landed as | stop line | fired? |
|---|---|---|---|
| 2. the rung `SeparationClause5Sum` | `Clause5.lean` §1–§3 (the pointwise bound, the infinite shell device, the crude majorant); `separation_clause5_summable`; Comparator PASS with nanoda | (a) the rung exceeds one session / the infinite shell device exceeds 300 lines | NO — the rung took 22:21–22:45 IST; §2 (the shell device) is 121 lines (`Clause5.lean` 147–267) |
| 3. 1(a) `Separation5` | `Clause5.lean` §4–§9; `ChallengeDeps/Separation5.lean` (`gammaPoly`, `Prelax`, `P2`, `P3`, `F13`, `HR0`); `separation_clause5_out_window`, `separation_clause6_assembly_c`; Comparator PASS | (b) any P₂/P₃/F₁₃ disagreement with the Python | NO — `verify-B/p23-diff.log`: |rel diff| = 0.0 for P₂, P₃ at L = 50, 100, 10³, 10⁴; F₁₃ at the record's b₁ identical to `Ftilde` (−0.322723205707068 at L = 50) |
| | | (c) the tail-integral `ring` identity does not close at n = 9 after two attempts | NO — the identity d/ds[e^{−as}γ_n(s)] = −sⁿe^{−as} is proved for EVERY n by induction through the recursion γ_{n+1} = s^{n+1}/a + ((n + 1)/a)γ_n (`gammaPoly_succ`), the inductive step closing by `field_simp; ring` at the first attempt; n = 9 is the general case |
| 4. 1(b) + Piece 8 `Separation5c` | `ZEnclosure.lean` (`Z_enclosure : 421/2000 ≤ Z ∧ Z ≤ 233651/10⁶`), `Clause5Cert.lean` (`F13_50_neg : HR0`); `separation_clause5_out_window_c`, `separation_clause6_assembly_d` (the two 1(a) statements with `hR0` removed, a NEW topic whose challenge imports the frozen `ChallengeDeps.Separation6b` only); Comparator PASS | (d) the 16-cell kernel check exceeds ten minutes | NO — `lake build Zeta23.Separation.ZEnclosure` 3.8 s wall, `…Clause5Cert` 3.4 s wall (`norm_num` over ℚ; numerators of 294 and 577 digits in `cert_numeric`) |
| plus | CONTROL PASS (`verify-B/control-run.log`); trust greps: the five deliberate challenge `sorry`s only; `#print axioms`: the standard three on the five roots and all 74 library theorems; Unit A's frozen statements byte-identical (sixteen lines) | CONTROL fails / trust-grep hit / axioms beyond the three / a frozen statement changes | NO ×4 |

Pricing observations, verified at the rung: (i) with the symbolic b₁ and the 16-cell upper bound on Z the one-point check has F₁₃(50; 73) = −0.347 at the enclosure endpoints (PRICING §0 (v): −0.349), against −0.3227 at the record's b₁ = 8.698 and −0.556 at b₁sym with exact constants (`verify-B/cert-numbers.log`, `p23-diff.log`); (ii) Piece 8 at n = 16 is 32 rational exp bounds and one `norm_num` call, seconds, as priced; (iii) the second conjunct of H-R₀, 5/(2c_B√73 − 13/8) ≤ 50, is a theorem with a wide margin (2c_B√73 − 13/8 = 0.818 ≥ 1/10) — it is kept in `HR0` because the note's one-point check has it and the decrease of F₁₃ on [50, ∞) is proved FROM it (`F13_le_F13_50`), not from the digits.

## 1. What was run, where, by what (brief rule 1)

* Runner `verify-B/run.sh` — a byte copy of `verify-A/run.sh` (comparator v4.33.0, lean4export v4.33.0-rc2, nanoda 0.4.17, `fake-landrun.sh` shim: NOT sandboxed, as `COMPARATOR-RUN.md` §2 explains). Every run from the repository root, `lake env comparator <config>`, comparator building the comparator-layer modules itself after the pre-run cleanup (`verify-B/prerun-cleanup.log`: the comparator-layer artifacts before the CONTROL run; the topic's artifacts and the top-level `Challenge`/`Solution`/`ChallengeDeps` oleans before each of the three runs).
* **CONTROL run (`comparator/config.json`, the parent's fifteen theorems): PASS** — `verify-B/control-run.log`, 22:10:53–22:13:58 IST, `184.73 real 145.45 user 19.72 sys`, lake `8699 jobs` / `8877 jobs` (identical to the D1, M4 (i), M4 (iii), Unit A records), `Nanoda kernel accepts the solution` / `Lean default kernel accepts the solution` / `Your solution is okay!`, exit 0. `lake build Zeta23` before any edit: *Build completed successfully (9150 jobs)*, 0 errors (`verify-B/lake-build-before.log`).
* Heavy compute: one `lake build` at a time; the three Comparator runs in the background one after another; nothing else CPU-heavy.

## 2. Files and declarations (line numbers; tree = mirror)

Sixteen new files; the ONE edit to an existing Lean file is the three additive imports in `Zeta23.lean` (`import Zeta23.Separation.Clause5`, `ZEnclosure`, `Clause5Cert`; `verify-B/untouched.log`). The old pairs (`Separation`, `SeparationG1`, `SeparationClause4`, `Separation6`, `SeparationClause4b`, `Separation6b`) and every trusted file of the earlier units are untouched (frozen-area `git diff --stat` empty) and on the frozen probe. `ChallengeDeps/Separation5.lean` IMPORTS the frozen `ChallengeDeps.Separation6b` and adds six definitions; `Challenge/SeparationClause5Sum.lean` and `Challenge/Separation5c.lean` import the frozen `ChallengeDeps.Separation6b` only (no new trusted definition). Full declaration list with line numbers: `verify-B/decls-B.txt`; the library files' theorems:

```
## Zeta23/Separation/Clause5.lean (1210 lines; imports Mathlib.Analysis.SumIntegralComparisons, Zeta23.Separation.Assembly2)
§1  60 Gmaj_antitone  86 norm_paperFT_ftest_le_strip  118 norm_wsum_le_strip
§2 147 shell_count_le  197 out_finset_sum_le  232 out_window_summable_tsum_le  256 out_window_norm_le
§3 271 pow16_mul_exp_le  283 def crudeM  285 crudeM_nonneg  290 crude_bound  321 crude_shell_bound  336 crude_series_le
   366 C1_nonneg_of_count  378 clause5_summable
§4 398 def gammaPoly  401 gammaPoly_zero  405 gammaPoly_succ  420 gammaPoly_nonneg  424 gammaPoly_mono  431 gammaPoly_mul_le
   445 hasDerivAt_exp_mul_gammaPoly  478 tendsto_exp_mul_gammaPoly  504 integral_pow_mul_exp_Ioi  522 def GammaM
   526 GammaM_nonneg  534 GammaM_mono  545 hasDerivAt_exp_mul_GammaM  557 tendsto_exp_mul_GammaM
§5 573 def phi  577 def Phi  580 phi_nonneg  584 phi_eq  593 hasDerivAt_Phi  611 tendsto_Phi  621 integral_phi_Ioi
   630 integrableOn_phi_Ioi
§6 643 gpow_antitone  683 phi_antitoneOn  700 sum_phi_le
§7 727 five_thirds_le_log_six  743 absorb_once  772 exp_neg_s0_le  793 pow_mul_Gmaj_sq_le
§8 813 def Prelax  821 def P2  824 def P3  828 def F13  833 def HR0  835 Prelax_pos  845 phi_tail_le  883 Prelax_mul_le
   938 slope_pos  948 F13_le_F13_50
§9 999 shell_weight_le  1016 shell_series_le  1137 clause5_out_window  1159 hL8_of_hL2  1179 clause6_assembly_c
## Zeta23/Separation/ZEnclosure.lean (188 lines; imports Mathlib.Analysis.SumIntegralComparisons, Zeta23.Separation.B1Sym)
38 Braw_antitoneOn  53 Braw_even  57 Z_eq_two_mul  69 sixteen_mul_Z  74 g_antitoneOn  82 riemann_bracket  95 def cellx
98 def qcell  100 Braw_cell  109 Braw_sixteen  113 exp_neg_le_inv_taylor  125 one_div_pow_le_exp_neg  131 def taylorT
134 exp_le_taylorT  140 cell_lo  149 cellx_le_qcell  156 Z_enclosure
## Zeta23/Separation/Clause5Cert.lean (234 lines; imports Clause5, ZEnclosure)
37–55 def eLo eHi cLo cHi rLo rHi ZLo ZHi CBHi b1Lo  57 eLo_le  60 le_eHi  63 cB_bounds  86 sqrt73_bounds  91 CB_le_CBHi
103 b1Lo_le_b1sym  123 gammaPoly_le  131 def PrelaxQ  138 Prelax_50_le  162 def ELo  165 cert_numeric  173 exp_ELo_ge
188 F13_50_neg
## comparator/ChallengeDeps/Separation5.lean (73 lines; imports Mathlib, ChallengeDeps.Separation6b)
45 def gammaPoly  49 def Prelax  57 def P2  60 def P3  64 def F13  69 def HR0
## comparator/Challenge/SeparationClause5Sum.lean 40 separation_clause5_summable (sorry 44) — Solution 31 — PrintAxioms 22
## comparator/Challenge/Separation5.lean 46 separation_clause5_out_window (sorry 51), 56 separation_clause6_assembly_c (sorry 69)
##   — Solution 35, 44 — PrintAxioms 20, 21
## comparator/Challenge/Separation5c.lean 43 separation_clause5_out_window_c (sorry 47), 51 separation_clause6_assembly_d (sorry 64)
##   — Solution 33, 41 — PrintAxioms 20, 21
## comparator/config-separation-clause5sum.json, config-separation5.json, config-separation5c.json
```

Decisions: (i) the infinite shell device (§2) is generic in a per-shell weight ψ(k) and a uniform bound c on the shell series over every initial segment Ico ⌊R⌋₊ K; both windows t ± (k + 1/2) count every shell, including shell 0 (Clause4.lean's shell-0 special case is not needed beyond the window); summability by `summable_of_sum_le` on finsets of the subtype (`Finset.sum_map` with `Function.Embedding.subtype`), the tsum bound by `Summable.tsum_le_of_sum_le`, the norm by `norm_tsum_le_tsum_norm`. (ii) The rung's crude majorant is e^{L/2}M_L/(k + 1)⁵, M_L := C_B²(1 + c_B²L)⁷8¹⁶/(c_B²L)⁷, from (1 + w)e^{−w/8} ≤ 8 and Σ(k + 1)⁻⁴ ≤ 2 (`sum_inv_pow_four_le'`, Clause4.lean, reused verbatim). (iii) The tail integral is taken in the u-variable: the antiderivative Φ_m(u) = −(2/L^{m+1})e^{−2c_B√(Lu)}Γ_m(√(Lu)) through the chain rule and `integral_Ioi_of_hasDerivAt_of_nonneg'` (which also gives the integrability); the substitution u = s²/L is inside `hasDerivAt_Phi`, not `integral_comp_mul_deriv_Ioi`; the s-form `integral_pow_mul_exp_Ioi` (the Mathlib-absent lemma) is stated and proved as well. (iv) No `deriv`: φ_m's antitonicity is the ratio bound g(s₂)/g(s₁) ≤ e^{d(2m/s₁ − c_B)} ≤ 1 (`gpow_antitone`), and the decrease of F₁₃ on [50, ∞) is the monomial comparison Q(50r) ≤ r⁵Q(50) (`gammaPoly_mul_le`, `Prelax_mul_le`) with log r ≤ r − 1 — the integrated form of the note's (log P)′ ≤ 5/L — using H-R₀'s second conjunct exactly as the note does. (v) `ChallengeDeps/Separation5.lean` adds `gammaPoly` and `Prelax` besides the four names of PRICING item 10: they are the script's `gamma_poly` and `P_relaxed`, and `P2`, `P3` are `Prelax 2`, `Prelax 3`; `F13` uses b₁sym (fidelity (r2)). (vi) 1(b) is a NEW topic `Separation5c` with new theorem names (`_c` for clause 5 without H-R₀, `_d` for the assembly with `houtZ`, `houtZ'` deleted), so that the 1(a) pair stays on disk unchanged as a shipped pair and the fourteen-plus-two earlier statements stay frozen; its challenge imports the frozen `ChallengeDeps.Separation6b` only. (vii) The certificate's per-cell lower bound uses q_i = ⌈x_i⌉ (1, 2, 3, 5, 9) rather than a uniform q, so that the decimal enclosure 421/2000 ≤ Z holds (a uniform q = 9 would lose 2.5·10⁻⁴ relative and cross 0.2105); the rationals are stated as decimals (`ZLo`, `ZHi`, `cLo`, …) and the exact sums are in `cert-numbers.log`. (viii) The label after 1(b) is the pricing's; the 1(a) label is recorded for the pair `Separation5` in the yaml and the ledger.

## 3. Checks (every acceptance line verbatim in the logs)

* **Builds.** `lake build Zeta23.Separation.Clause5`: *2846 jobs*, 0 errors, 0 warnings from the module. `…ZEnclosure`: *2843 jobs*, 3.8 s wall. `…Clause5Cert`: *2848 jobs*, 3.4 s wall. `lake build Solution.SeparationClause5Sum`: *8711 jobs*; `Solution.Separation5`: *8712 jobs*; `Solution.Separation5c`: *8713 jobs*; all 0 errors. Full `lake build Zeta23` after the root imports: **9153 jobs** (Unit A's 9150 plus three), 0 errors (`verify-B/lake-build.log`).
* **`#print axioms`.** The five root theorems (`verify-B/print-axioms-clause5sum.log`, `print-axioms-separation5.log`, `print-axioms-separation5c.log`): `[propext, Classical.choice, Quot.sound]` ×5. Every theorem of `Clause5.lean`, `ZEnclosure.lean`, `Clause5Cert.lean` — 74 theorems (`verify-B/print-axioms-library-B.log`, probe `axioms_B_probe.lean.txt`): the standard three ×74, nothing else.
* **Trust greps** (`verify-B/trust_greps_B.py`, comments stripped, thirteen Lean files; `trust-greps-B.log`, and per leg `trust-greps-B-rung.log`, `-1a.log`, `-1b.log`): exactly the five deliberate challenge `sorry`s (`SeparationClause5Sum.lean` 44; `Separation5.lean` 51, 69; `Separation5c.lean` 47, 64).
* **Statement identity** (`statement_identity_B.py`): `separation_clause5_summable` 222 bytes IDENTICAL (`statement-identity-clause5sum.log`); `separation_clause5_out_window` 263, `separation_clause6_assembly_c` 846 (`statement-identity-separation5.log`); `separation_clause5_out_window_c` 238, `separation_clause6_assembly_d` 823 (`statement-identity-separation5c.log`); RESULT PASS ×3.
* **Fidelity (r2), the term-for-term diff** (`verify-B/p23_diff.py` → `p23-diff.log`): the Lean definitions transcribed line by line (each Python line annotated with the Lean text) against `r0_73_check.py` lines 22–33 exec'd verbatim from the file, at L = 50, 100, 10³, 10⁴: **|rel diff| = 0.0 for P₂ and P₃ at all four L; F₁₃ at the record's b₁ identical to `Ftilde`; RESULT PASS.** F₁₃ at b₁sym: −0.5561, −38.06, −762.7, −8112.4.
* **The certificate's numbers** (`verify-B/cert_numbers.py` → `cert-numbers.log`, exact rationals): c_B ∈ [14296064739, 14296064759]·10⁻¹¹, √73 ∈ [427200187261, 427200187271]/(5·10¹⁰); the 16 cells (x_i, q_i, lo_i, hi_i listed); Z_lo = 0.2105014 (−5.18 %), Z_hi = 0.2336502 (+5.25 %); the decimal enclosure 421/2000 ≤ Z ≤ 233651/10⁶; E_lo = 40.8622; F₁₃(50) at the endpoints = −0.3474; the certificate inequality Q_hi/b₁_lo ≤ e_lo⁴⁰·Σ_{i<6}(E_lo − 40)^i/i! holds with 0.347 nats to spare.
* **Frozen probe** (`verify-B/frozen_probe.lean.txt` → `frozen-statements.log`): the twelve of Unit A's probe — the body of `verify-A/frozen-statements.log` is a byte-identical prefix of Unit B's log — plus Unit A's two root pairs (`separation_clause4_in_window_noise_b`; `separation_clause6_assembly_b`, `separation_clause7_tight_pair`, `rstar_of_21L`): sixteen `#print axioms` lines, all on the standard three.
* **Comparator run, topic `SeparationClause5Sum` (`verify-B/comparator-run-clause5sum.log`): PASS** — `Built Challenge.SeparationClause5Sum` with its one deliberate `sorry` warning, *8701 jobs*; `Built Solution.SeparationClause5Sum`, *8711 jobs*; `Nanoda kernel accepts the solution` / `Lean default kernel accepts the solution` / `Your solution is okay!`; `73.89 real 67.08 user 12.56 sys`; `--- comparator exit code: 0 ---` (22:29:54 IST).
* **Comparator run, topic `Separation5` (`verify-B/comparator-run-separation5.log`): PASS** — `Built ChallengeDeps.Separation5`, `Built Challenge.Separation5` with its two `sorry` warnings, *8702 jobs*; export of `separation_clause5_out_window separation_clause6_assembly_c`; `Built Solution.Separation5`, *8712 jobs*; the three acceptance lines; `79.58 real 71.74 user 13.92 sys`; exit 0 (22:49:15 IST).
* **Comparator run, topic `Separation5c` (`verify-B/comparator-run-separation5c.log`): PASS** — `Built Challenge.Separation5c` with its two `sorry` warnings, *8701 jobs*; export of `separation_clause5_out_window_c separation_clause6_assembly_d`; `Built Solution.Separation5c`, *8713 jobs*; the three acceptance lines; `107.37 real 73.92 user 15.98 sys`; exit 0 (22:57:58 IST). Five shim `WARNING: THIS IS NOT REAL LANDRUN!` lines per run (not sandboxed, as in the D1 record).
* **Untouched** (`verify-B/untouched.log`): `git status` of `lean/` shows only the new files and the root's three imports; `git diff --stat HEAD` over the frozen areas (M4 (i), M4 (iii), Unit A pairs; DBN, W1, PairCeiling; `LemmaG1`, `LemmaG`, `Clause4`, `Assembly`, `B1Sym`, `Assembly2`; `SepConfig`, `Separation6`, `Separation6b` deps; all configs) empty; tree = mirror for 58 files + `formalization.yaml`.
* **10(g) lint:** no "clearly / obviously / easy to see / well known" and no British spellings in the sixteen files, FIDELITY (r), the yaml additions or the SHARED blocks (grep at packaging).

## 4. Packaging

* **`lean/formalization.yaml`** (976 after the rung → 1110 lines; tree copy `cmp`-identical): project description (the Unit B paragraph with the label), `status.scope` (the five new challenge `sorry`s named; what each Session 25 topic takes as displayed — H-out displayed nowhere in them), three `main_results` entries (the rung; 1(a); 1(b) + Piece 8), fidelity paragraph (r) with (r1)–(r6), three `review.notes` paragraphs quoting the runs (`review.status` stays `self-assessed`), three `alignment.statements` rows. Validation (`verify-B/yaml-validation.log`, `results/d1-m2a/dr8/validate_yaml_sigma_strong.py`, the upstream schema re-fetched and IDENTICAL): **VALIDATION errors: 0; RESULT: PASS — errors: 0, undeclared names: 0** (main_results 27, alignment.statements 28).
* **`results/d1-m2a/packaging/FIDELITY.md`**: section (r) appended — (r3), (r4) at the rung, (r1), (r2), (r5), (r6) at 1(a)/1(b) (70 lines now).
* **Fidelity, in one line each:** (r1) H-out → H-R₀ (`Separation5`) → nothing (`Separation5c`); (q1) superseded for the Session 25 topics. (r2) `gammaPoly`, `Prelax`, `P2`, `P3`, `F13` = `r0_73_check.py` 22–33 term for term (diff at four L: 0.0), b₁ = b₁sym; the proof departs from the note's calculus only in method (monomial comparison, ratio bound, chain rule), never in a statement. (r3) `strip` consumed for the first time (the depth enters through e^{L|y′|/2} ≤ e^{L/4}); (q5) amended. (r4) the shell index starts at ⌊73L⌋₊ ≥ 73L − 1; every shell by the two windows at t ± (k + 1/2). (r5) the absorption spent once, exponent 13/8, R₀ = 73 (A3), not the body's 7/4 / 81; clause 5's L-hypothesis 8(log log(3 + t) + log(2b₁C₁)) ≤ L from the assembly's. (r6) 421/2000 ≤ Z ≤ 233651/10⁶ PROVED (16 cells), consumed by `F13_50_neg` only.
* Files written under `results/c2-m4/`: `BUILD-NOTES-B.md` (this file), `hashes-B.txt`, the Unit B blocks of `SHARED.md` (stages 0–7), `verify-B/{run.sh, prerun-cleanup.log, control-run.log, lake-build-before.log, lake-build.log, comparator-run-clause5sum.log, comparator-run-separation5.log, comparator-run-separation5c.log, print-axioms-clause5sum.log, print-axioms-separation5.log, print-axioms-separation5c.log, print-axioms-library-B.log, axioms_B_probe.lean.txt, statement_identity_B.py, statement-identity-clause5sum.log, statement-identity-separation5.log, statement-identity-separation5c.log, trust_greps_B.py, trust-greps-B.log, trust-greps-B-rung.log, trust-greps-B-1a.log, trust-greps-B-1b.log, p23_diff.py, p23-diff.log, cert_numbers.py, cert-numbers.log, frozen_probe.lean.txt, frozen-statements.log, untouched.log, yaml-validation.log, decls-B.txt}`.

## 5. What an independent checker from a clean clone must do (Job 2, Opus 5; `CHECK-O-B.md`)

1. Clone `anthropics/zeta-23-lean` at tag `v1.0`, overlay `rh-program/lean/Zeta23/`, `lean/comparator/`, `lean/Zeta23.lean`, `lean/formalization.yaml` as `lean/README.md` says; `lake exe cache get`; `lake build Zeta23` (expect *9153 jobs*, 0 errors); `lake build Solution.SeparationClause5Sum Solution.Separation5 Solution.Separation5c`. Time `lake build Zeta23.Separation.ZEnclosure` and `…Clause5Cert` cold (expect seconds; stop line (d) is ten minutes).
2. `lake env lean comparator/PrintAxioms/{SeparationClause5Sum,Separation5,Separation5c}.lean`: five lines, each `[propext, Classical.choice, Quot.sound]`; the probe `verify-B/axioms_B_probe.lean.txt` on all 74 theorems of the three library files.
3. Trust greps (`verify-B/trust_greps_B.py <clone-root> <the thirteen Lean files>`): exactly the five challenge `sorry`s. Statement identity (`statement_identity_B.py`) for the three topics. That `ChallengeDeps/Separation5.lean` imports the frozen `ChallengeDeps.Separation6b` and re-declares nothing, and that `Challenge/SeparationClause5Sum.lean` and `Challenge/Separation5c.lean` import `ChallengeDeps.Separation6b` only. The character-for-character claim: `Separation.{gammaPoly, Prelax, P2, P3, F13, HR0}` (`ChallengeDeps/Separation5.lean`) versus `Zeta23.Separation.{…}` (`Clause5.lean` 398–833) — `diff` of the `def` blocks.
4. The five items the brief weighs hardest: (i) `P2`, `P3`, `F13` in Lean equal `r0_73_check.py` 22–33 term for term — re-run `verify-B/p23_diff.py` (it exec's the script's lines verbatim) and read both texts side by side; the b₁ substitution (b₁sym for 8.69808) and 105/100 for 1.05 are the only differences, both declared in (r2). (ii) The tail-integral antiderivative identity (`gammaPoly_succ`, `hasDerivAt_exp_mul_gammaPoly`) and the limit at +∞ (`tendsto_exp_mul_gammaPoly`); a paper re-derivation of aγ_n − γ_n′ = sⁿ and of the chain rule in `hasDerivAt_Phi` (Ψ′(s)·L/(2s) = φ_m(u) with s² = Lu). (iii) `HR0` is exactly the note's one-point check at R₀ = 73 with the exponent 13/8 (A3): `F13 50 ≤ 0 ∧ 5/(2·cB·√73 − 13/8) ≤ 50`; the assembly's conclusion is unchanged (diff `separation_clause6_assembly_c` / `_d` against `separation_clause6_assembly_b`: `houtZ`, `houtZ'` → `hR0` → nothing, nothing else); the absorption is spent once (`absorb_once` against A3's sentence). (iv) For 1(b), recompute Z_lo, Z_hi and F₁₃(50) at the endpoints on your own code (`cert_numbers.py` is the builder's; write your own): the 16 cells x_i = 256/(256 − i²), the two Taylor bounds at n = 8 with q_i = ⌈x_i⌉, and the endpoint substitution; check that `cert_numeric`'s inequality is the one `F13_50_neg` consumes and that its margin is ≈ 0.347 nats. (v) The `strip` field is consumed exactly where (r3) says (`norm_wsum_le_strip`, `Clause5.lean` 118; passed as `Z.strip` in the three solution files) and nowhere else new.
5. The four Comparator runs with nanoda from the clean clone (`verify-B/run.sh` pattern; do NOT pre-build the comparator layer): CONTROL first, then `config-separation-clause5sum.json`, `config-separation5.json` (two theorem names), `config-separation5c.json` (two theorem names).
6. The sixteen frozen statements (`verify-B/frozen_probe.lean.txt`) against `verify-B/frozen-statements.log` and `verify-A/frozen-statements.log`; the yaml schema validation; 10(g) lint; the labels (the 1(a) label for `Separation5`, the 1(b) label for `Separation5c`) honest everywhere, never "Theorem M2 is formalized".

## 6. SHA-256 (`hashes-B.txt`; this file's own hash is in `SHARED.md`'s final Unit B block and in the chat report)
